### ISSUE TITLE
Python version standardization

### ISSUE THREAD

**Issue by farewelldave** [StrongholdData/Stronghold-Cloud-Reporting#7]
@benmcnelly: I have been modifying code snippets to be pep8 compatible (based on python style guides), as I'm still learning python/django, and not wanting to go too far down the path.

However, I believe you're using python 2.x for doing your development. There aren't too many things that are breaking yet, but a few of the modifications I've made (https://github.com/StrongholdData/Stronghold-Cloud-Reporting/commit/ffc728d4e5fc45e406ee4294c2b4f32d7677b97e) where the modifications are Python 3 specific to catch the exception `except ImportError as e:` instead of `except ImportError, e:`

Also, [xhtml2pdf](https://github.com/xhtml2pdf/xhtml2pdf) lib isn't working correctly in python 3 yet, but they are working on it, and I was able to run: `pip install --pre xhtml2pdf` to get python 3 support.

I feel like that's the tip of the iceberg however, and to me since this is a new project, it would make sense to ensure python 3 compatibility - as that is the one that will be sticking around. I'm open to suggestions, and while technical end-of-life of Python 2 is [2020](https://pythonclock.org/), Python maintainers [state](https://wiki.python.org/moin/Python2orPython3):
>Python 2.x is legacy, Python 3.x is the present and future of the language

Others feel like Python 2 is the Windows XP of programming; it's everywhere, but will become an issue from a security perspective as it is being replaced by Python 3.

So, all that to say, I think we need to make sure we standardize on a version, as there are some breaking changes that while django helps smooth the rough edges, just stating which python version we are going to standardize on, will help as we create and refine the code.

**Comment by benmcnelly** [comment]
Yes I agree, won't be a big deal to spin up an new virtualenv and pull down the project and just start using 3, I don't think we will run into anything not ready for 3, and if so there is always an alternative.

**Comment by benmcnelly** [comment]
Alright I have moved to a python 3 virtualenv, and will rewrite the PDF reports to go from xhtml2pdf to using weasyprint. We will then have only python 3 compatible libraries!  :snake:

**Comment by benmcnelly** [comment]
Completely moved to Python 3, closing this out!
