### ISSUE TITLE
Static asset linking in templates

### ISSUE THREAD

**Issue by farewelldave** [StrongholdData/Stronghold-Cloud-Reporting#8]
I see many sources for images, etc. in the templates as linked to a local IP.

I have changed base.html in templates to go from this:

```html
<!-- Bootstrap core CSS     -->
    <link href="http://10.223.45.59:8000/static/paper-dashboard/assets/css/bootstrap.min.css" rel="stylesheet" />
```

to this:

```python
    {% load static %}
    
    # as needed, reference the static link
    <link href="{% static "paper-dashboard/assets/css/bootstrap.min.css" %}" rel="stylesheet" />
```

Works fine on my machine, and moving forward, this should work provided the STATIC settings in settings.py/settings_local.py are defined correctly.

**Comment by benmcnelly** [comment]
looks good, and eventually we want to probably set a tag up for default site url too
